import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
// import header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" top-0 z-50 sticky">

       <Navbar/>
       {/* <Footer/> */}
        </div>
       {/* <h1>hello</h1> */}
        {children}</body>
    </html>
  );
}
